name: Deploy the model

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install langchain
          pip install faiss-cpu
          pip install openai
          pip install llama_index

      - name: Deploy the model
        run: |
          # Set the OpenAI API key
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

          # Run your streamlit application
          streamlit run your_streamlit_app.py
